version: "3"
services:
  mta-server:
    image: notfound/mtasa-server:latest
    container_name: mta_server

    stdin_open: true # https://stackoverflow.com/a/39150040
    tty: true
    
    ports:
      - 22005:22005
      - "22003:22003/udp"
      - "22126:22126/udp"
    volumes:
      - ./mta_server/data:/data
      - ./mta_server/resources:/resources
      - ./mta_server/modules:/native-modules
    environment:
      - DB_HOST=${DB_HOST?:Env var DB_HOST nije namešten.}
      - DB_USER=${DB_USER?:Env var DB_USER nije namešten.}
      - DB_NAME=${MYSQL_DATABASE?:Env var MYSQL_DATABASE nije namešten.}
      - DB_PASS=${DB_PASS?Env var DB_PASS nije namešten.}
    depends_on:
      - mysql-server
    command: ["echo", "sta se desava", "&&", "/mtasa/mods/deathmatch/scripts/wait-for", "${DB_HOST}:3306", "--", "echo", "DOBRO JEEEEEEEEE"]

  mysql-server:
    image: mysql:latest
    container_name: mysql_server

    ports:
      - 3306:3306
    volumes:
      - ./mysql_server:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=${MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      - MYSQL_ONETIME_PASSWORD=${MYSQL_ONETIME_PASSWORD}
      - MYSQL_INITDB_SKIP_TZINFO=${MYSQL_INITDB_SKIP_TZINFO}