version: "3"
services:
  mta-server:
    image: notfound/mtasa-server:latest
    container_name: mta_server

    stdin_open: true # https://stackoverflow.com/a/39150040
    tty: true
    
    ports:
      - 22005:22005
      - "22003:22003/udp"
      - "22126:22126/udp"
    volumes:
      - ./mta_server/data:/data
      - ./mta_server/resources:/resources
      - ./mta_server/modules:/native-modules
    environment:
      - DB_HOST=${DB_HOST?:Env var DB_HOST nije namešten.}
      - DB_USER=${DB_USER?:Env var DB_USER nije namešten.}
      - DB_NAME=${DB_NAME?:Env var DB_NAME nije namešten.}
      - DB_PASS=${DB_PASS?:Env var DB_PASS nije namešten.}